### ISSUE TITLE
error - "An error occurred trying to start process 'cmd.exe' with working directory '/home/filip'. No such file or directory"

### ISSUE THREAD

**Issue by filip2cz** [3ncy/NetworkExplorer#1]
same issue on: 
- Linux - GeckoLinux Rolling, kernel 5.16.1-1-default
- Linux - Linux Mint 20.02, kernel 5.4.0-91-generic

```
Oskenovana IP 192.168.1.107 a host je zapnuty
Unhandled exception. System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'cmd.exe' with working directory '/home/filip'. No such file or directory)
 ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'cmd.exe' with working directory '/home/filip'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NetworkExplorer.Explorer.GetMACAndManufacturerAsync(Byte[] ip)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NetworkExplorer.Program.Main(String[] args)
Neúspěšně ukončen (SIGABRT) (core dumped [obraz paměti uložen])
```

**Comment by 3ncy** [comment]
Ah shit, máš recht. Na to nějak nezbyl čas při vývoji. Až teď dodělám urgentnější věci, tak na to kouknu
